name: 'Pull Requests'
on:
  - pull_request
env:
  TF_VERSION: ~1.0
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v1
        with:
          configFile: ./.commitlintrc.json